// Automatically generated by zod_gen
import * as z from 'zod';

export const AddReactionInputSchema = z.object({
  kind: z.string(),
  value: z.string(),
  image_url: z.string().optional()
});
export type AddReactionInput = z.infer<typeof AddReactionInputSchema>;

export const AllowDmsSchema = z.enum(['open', 'friends_only', 'closed']);
export type AllowDms = z.infer<typeof AllowDmsSchema>;

export const AllowFriendRequestsSchema = z.enum(['open', 'mutual', 'closed']);
export type AllowFriendRequests = z.infer<typeof AllowFriendRequestsSchema>;

export const AttachmentSchema = z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
});
export type Attachment = z.infer<typeof AttachmentSchema>;

export const AuditActionSchema = z.enum(['message_delete', 'message_purge', 'member_kick', 'member_ban', 'member_unban', 'member_role_add', 'member_role_remove', 'role_create', 'role_update', 'role_delete', 'channel_create', 'channel_update', 'channel_delete', 'channel_restore', 'channel_hard_delete', 'role_restore', 'role_hard_delete', 'message_restore', 'message_hard_delete', 'server_update', 'server_transfer_ownership', 'invite_create', 'invite_update', 'invite_delete']);
export type AuditAction = z.infer<typeof AuditActionSchema>;

export const AuditLogSchema = z.object({
  id: z.string(),
  server_id: z.string(),
  actor_id: z.string(),
  action: z.enum(['message_delete', 'message_purge', 'member_kick', 'member_ban', 'member_unban', 'member_role_add', 'member_role_remove', 'role_create', 'role_update', 'role_delete', 'channel_create', 'channel_update', 'channel_delete', 'channel_restore', 'channel_hard_delete', 'role_restore', 'role_hard_delete', 'message_restore', 'message_hard_delete', 'server_update', 'server_transfer_ownership', 'invite_create', 'invite_update', 'invite_delete']),
  target_kind: z.enum(['message', 'member', 'role', 'channel', 'server', 'invite']),
  target_id: z.string().optional(),
  target_user_id: z.string().optional(),
  channel_id: z.string().optional(),
  metadata: z.record(z.string(), z.any()),
  reason: z.string().optional(),
  batch_id: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
});
export type AuditLog = z.infer<typeof AuditLogSchema>;

export const AuditTargetKindSchema = z.enum(['message', 'member', 'role', 'channel', 'server', 'invite']);
export type AuditTargetKind = z.infer<typeof AuditTargetKindSchema>;

export const BanMemberInputSchema = z.object({
  user_id: z.string(),
  reason: z.string().optional(),
  delete_seconds: z.number().optional()
});
export type BanMemberInput = z.infer<typeof BanMemberInputSchema>;

export const BlockedRowSchema = z.object({
  blocker_id: z.string(),
  blocked_id: z.string(),
  created_at: z.string()
});
export type BlockedRow = z.infer<typeof BlockedRowSchema>;

export const CategoryReorderInputSchema = z.object({
  categoryIds: z.array(z.string())
});
export type CategoryReorderInput = z.infer<typeof CategoryReorderInputSchema>;

export const ChannelSchema = z.object({
  id: z.string(),
  type: z.enum(['text', 'voice', 'direct', 'group']),
  name: z.string().optional(),
  topic: z.string().optional(),
  server_id: z.string().optional(),
  category_id: z.string().optional(),
  position: z.number(),
  created_by: z.string(),
  last_message_at: z.string().optional(),
  deleted: z.boolean(),
  deleted_at: z.string().optional(),
  deleted_by: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string(),
  my_permissions: z.string().optional()
});
export type Channel = z.infer<typeof ChannelSchema>;

export const ChannelCategorySchema = z.object({
  id: z.string(),
  server_id: z.string(),
  name: z.string(),
  position: z.number(),
  created_at: z.string(),
  updated_at: z.string()
});
export type ChannelCategory = z.infer<typeof ChannelCategorySchema>;

export const ChannelParticipantSchema = z.object({
  id: z.string(),
  channel_id: z.string(),
  user_id: z.string(),
  role: z.enum(['owner', 'admin', 'member']),
  last_read_at: z.string().optional(),
  joined_at: z.string(),
  created_at: z.string(),
  updated_at: z.string()
});
export type ChannelParticipant = z.infer<typeof ChannelParticipantSchema>;

export const ChannelReorderInputSchema = z.object({
  channelIds: z.array(z.string()),
  categoryId: z.string().optional()
});
export type ChannelReorderInput = z.infer<typeof ChannelReorderInputSchema>;

export const ChannelTypeSchema = z.enum(['text', 'voice', 'direct', 'group']);
export type ChannelType = z.infer<typeof ChannelTypeSchema>;

export const CreateCategoryInputSchema = z.object({
  name: z.string()
});
export type CreateCategoryInput = z.infer<typeof CreateCategoryInputSchema>;

export const CreateChannelInputSchema = z.object({
  name: z.string(),
  type: z.string().optional(),
  category_id: z.string().optional()
});
export type CreateChannelInput = z.infer<typeof CreateChannelInputSchema>;

export const CreateDmInputSchema = z.object({
  recipient_id: z.string(),
  syr_instance_url: z.string().optional()
});
export type CreateDmInput = z.infer<typeof CreateDmInputSchema>;

export const CreateDmResponseSchema = z.object({
  id: z.string(),
  type: z.string()
});
export type CreateDmResponse = z.infer<typeof CreateDmResponseSchema>;

export const CreateInviteInputSchema = z.object({
  max_uses: z.number().optional(),
  expires_in: z.number().optional(),
  target_kind: z.enum(['open', 'instance', 'did']).optional(),
  target_value: z.string().optional(),
  label: z.string().optional()
});
export type CreateInviteInput = z.infer<typeof CreateInviteInputSchema>;

export const CreateInviteResponseSchema = z.object({
  code: z.string()
});
export type CreateInviteResponse = z.infer<typeof CreateInviteResponseSchema>;

export const CreateRoleInputSchema = z.object({
  name: z.string(),
  color: z.string().optional(),
  permissions: z.string().optional(),
  permissions_allow: z.string().optional(),
  permissions_deny: z.string().optional()
});
export type CreateRoleInput = z.infer<typeof CreateRoleInputSchema>;

export const CreateServerInputSchema = z.object({
  name: z.string(),
  icon_url: z.string().optional(),
  banner_url: z.string().optional(),
  invite_background_url: z.string().optional(),
  description: z.string().optional()
});
export type CreateServerInput = z.infer<typeof CreateServerInputSchema>;

export const DmChannelSummarySchema = z.object({
  id: z.string(),
  type: z.string(),
  last_message_at: z.string().optional(),
  other_user_id: z.string().optional(),
  other_user_instance_url: z.string().optional(),
  is_blocked: z.boolean(),
  is_ignored: z.boolean()
});
export type DmChannelSummary = z.infer<typeof DmChannelSummarySchema>;

export const EditMessageInputSchema = z.object({
  content: z.string()
});
export type EditMessageInput = z.infer<typeof EditMessageInputSchema>;

export const EmbedSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  url: z.string().optional(),
  thumbnail_url: z.string().optional(),
  site_name: z.string().optional(),
  color: z.string().optional(),
  embed_url: z.string().optional()
});
export type Embed = z.infer<typeof EmbedSchema>;

export const ExchangeRequestSchema = z.object({
  code: z.string()
});
export type ExchangeRequest = z.infer<typeof ExchangeRequestSchema>;

export const ExchangeResponseSchema = z.object({
  session: z.string()
});
export type ExchangeResponse = z.infer<typeof ExchangeResponseSchema>;

export const FriendSendInputSchema = z.object({
  user_id: z.string(),
  syr_instance_url: z.string().optional()
});
export type FriendSendInput = z.infer<typeof FriendSendInputSchema>;

export const FriendshipSchema = z.object({
  id: z.string(),
  user_a_id: z.string(),
  user_b_id: z.string(),
  status: z.enum(['pending', 'accepted']),
  requested_by: z.string(),
  created_at: z.string(),
  updated_at: z.string()
});
export type Friendship = z.infer<typeof FriendshipSchema>;

export const FriendshipRowSchema = z.object({
  user_id: z.string()
});
export type FriendshipRow = z.infer<typeof FriendshipRowSchema>;

export const FriendshipStatusSchema = z.enum(['pending', 'accepted']);
export type FriendshipStatus = z.infer<typeof FriendshipStatusSchema>;

export const IdentitySchema = z.object({
  did: z.string(),
  syr_instance_url: z.string(),
  delegate_public_key: z.string().optional(),
  trusted_domains: z.array(z.string()),
  allow_dms: z.string().optional(),
  allow_friend_requests: z.string().optional()
});
export type Identity = z.infer<typeof IdentitySchema>;

export const IgnoredRowSchema = z.object({
  user_id: z.string(),
  ignored_id: z.string(),
  created_at: z.string()
});
export type IgnoredRow = z.infer<typeof IgnoredRowSchema>;

export const InviteJoinResponseSchema = z.object({
  server_id: z.string()
});
export type InviteJoinResponse = z.infer<typeof InviteJoinResponseSchema>;

export const InvitePreviewSchema = z.object({
  code: z.string(),
  target_kind: z.enum(['open', 'instance', 'did']),
  target_value: z.string().optional(),
  label: z.string().optional(),
  server: z.object({
  id: z.string(),
  name: z.string(),
  icon_url: z.string().optional(),
  banner_url: z.string().optional(),
  invite_background_url: z.string().optional(),
  description: z.string().optional(),
  member_count: z.number()
})
});
export type InvitePreview = z.infer<typeof InvitePreviewSchema>;

export const InvitePreviewServerSchema = z.object({
  id: z.string(),
  name: z.string(),
  icon_url: z.string().optional(),
  banner_url: z.string().optional(),
  invite_background_url: z.string().optional(),
  description: z.string().optional(),
  member_count: z.number()
});
export type InvitePreviewServer = z.infer<typeof InvitePreviewServerSchema>;

export const InviteTargetKindSchema = z.enum(['open', 'instance', 'did']);
export type InviteTargetKind = z.infer<typeof InviteTargetKindSchema>;

export const KickMemberQuerySchema = z.object({
  delete_seconds: z.number().optional()
});
export type KickMemberQuery = z.infer<typeof KickMemberQuerySchema>;

export const LoginRequestSchema = z.object({
  instance_url: z.string(),
  redirect: z.string().optional()
});
export type LoginRequest = z.infer<typeof LoginRequestSchema>;

export const LoginResponseSchema = z.object({
  consent_url: z.string()
});
export type LoginResponse = z.infer<typeof LoginResponseSchema>;

export const MarkChannelReadInputSchema = z.object({
  last_message_id: z.string()
});
export type MarkChannelReadInput = z.infer<typeof MarkChannelReadInputSchema>;

export const MemberMessageEntrySchema = z.object({
  id: z.string(),
  channel_id: z.string(),
  channel_name: z.string().optional(),
  sender_id: z.string(),
  content: z.string(),
  created_at: z.string(),
  edited_at: z.string().optional(),
  attachments: z.array(z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
}))
});
export type MemberMessageEntry = z.infer<typeof MemberMessageEntrySchema>;

export const MemberMessagePerChannelSchema = z.object({
  channel_id: z.string(),
  channel_name: z.string().optional(),
  count: z.number()
});
export type MemberMessagePerChannel = z.infer<typeof MemberMessagePerChannelSchema>;

export const MemberMessageStatsSchema = z.object({
  total: z.number(),
  first_at: z.string().optional(),
  last_at: z.string().optional(),
  per_channel: z.array(z.object({
  channel_id: z.string(),
  channel_name: z.string().optional(),
  count: z.number()
}))
});
export type MemberMessageStats = z.infer<typeof MemberMessageStatsSchema>;

export const MemberPermissionsViewSchema = z.object({
  permissions: z.string(),
  permissions_allow: z.string(),
  permissions_deny: z.string(),
  highest_role_position: z.number(),
  is_owner: z.boolean(),
  visible_channels: z.array(z.object({
  id: z.string(),
  name: z.string(),
  type: z.string()
}))
});
export type MemberPermissionsView = z.infer<typeof MemberPermissionsViewSchema>;

export const MessageSchema = z.object({
  id: z.string(),
  channel_id: z.string(),
  sender_id: z.string(),
  type: z.enum(['text', 'system', 'reply']),
  content: z.string(),
  edited_at: z.string().optional(),
  reply_to: z.array(z.string()),
  attachments: z.array(z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
})),
  embeds: z.array(z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  url: z.string().optional(),
  thumbnail_url: z.string().optional(),
  site_name: z.string().optional(),
  color: z.string().optional(),
  embed_url: z.string().optional()
})),
  reactions: z.array(z.object({
  value: z.string(),
  count: z.number(),
  me: z.boolean(),
  kind: z.string().optional(),
  image_url: z.string().optional()
})),
  pinned: z.boolean(),
  signature: z.string().optional(),
  signer_did: z.string().optional(),
  signer_delegate_key: z.string().optional(),
  sender_instance_url: z.string().optional(),
  deleted: z.boolean(),
  deleted_at: z.string().optional(),
  deleted_by: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
});
export type Message = z.infer<typeof MessageSchema>;

export const MessageReactionSchema = z.object({
  id: z.string(),
  message_id: z.string(),
  user_id: z.string(),
  kind: z.enum(['unicode', 'custom_emoji']),
  value: z.string(),
  image_url: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
});
export type MessageReaction = z.infer<typeof MessageReactionSchema>;

export const MessageTypeSchema = z.enum(['text', 'system', 'reply']);
export type MessageType = z.infer<typeof MessageTypeSchema>;

export const MyPermissionsSchema = z.object({
  permissions: z.string(),
  permissions_allow: z.string(),
  permissions_deny: z.string(),
  highest_role_position: z.number(),
  is_owner: z.boolean()
});
export type MyPermissions = z.infer<typeof MyPermissionsSchema>;

export const PageAuditLogSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  server_id: z.string(),
  actor_id: z.string(),
  action: z.enum(['message_delete', 'message_purge', 'member_kick', 'member_ban', 'member_unban', 'member_role_add', 'member_role_remove', 'role_create', 'role_update', 'role_delete', 'channel_create', 'channel_update', 'channel_delete', 'channel_restore', 'channel_hard_delete', 'role_restore', 'role_hard_delete', 'message_restore', 'message_hard_delete', 'server_update', 'server_transfer_ownership', 'invite_create', 'invite_update', 'invite_delete']),
  target_kind: z.enum(['message', 'member', 'role', 'channel', 'server', 'invite']),
  target_id: z.string().optional(),
  target_user_id: z.string().optional(),
  channel_id: z.string().optional(),
  metadata: z.record(z.string(), z.any()),
  reason: z.string().optional(),
  batch_id: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
})),
  total: z.number()
});
export type PageAuditLog = z.infer<typeof PageAuditLogSchema>;

export const PageBlockedRowSchema = z.object({
  items: z.array(z.object({
  blocker_id: z.string(),
  blocked_id: z.string(),
  created_at: z.string()
})),
  total: z.number()
});
export type PageBlockedRow = z.infer<typeof PageBlockedRowSchema>;

export const PageFriendshipRowSchema = z.object({
  items: z.array(z.object({
  user_id: z.string()
})),
  total: z.number()
});
export type PageFriendshipRow = z.infer<typeof PageFriendshipRowSchema>;

export const PageIgnoredRowSchema = z.object({
  items: z.array(z.object({
  user_id: z.string(),
  ignored_id: z.string(),
  created_at: z.string()
})),
  total: z.number()
});
export type PageIgnoredRow = z.infer<typeof PageIgnoredRowSchema>;

export const PageMemberMessageEntrySchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  channel_id: z.string(),
  channel_name: z.string().optional(),
  sender_id: z.string(),
  content: z.string(),
  created_at: z.string(),
  edited_at: z.string().optional(),
  attachments: z.array(z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
}))
})),
  total: z.number()
});
export type PageMemberMessageEntry = z.infer<typeof PageMemberMessageEntrySchema>;

export const PageServerBanSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  server_id: z.string(),
  user_id: z.string(),
  banned_by: z.string(),
  banned_at: z.string(),
  reason: z.string().optional(),
  active: z.boolean(),
  unbanned_at: z.string().optional(),
  unbanned_by: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
})),
  total: z.number()
});
export type PageServerBan = z.infer<typeof PageServerBanSchema>;

export const PageServerInviteSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  server_id: z.string(),
  code: z.string(),
  created_by: z.string(),
  expires_at: z.string().optional(),
  max_uses: z.number(),
  uses: z.number(),
  target_kind: z.enum(['open', 'instance', 'did']),
  target_value: z.string().optional(),
  label: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
})),
  total: z.number()
});
export type PageServerInvite = z.infer<typeof PageServerInviteSchema>;

export const PageServerMemberSchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  server_id: z.string(),
  user_id: z.string(),
  nickname: z.string().optional(),
  role_ids: z.array(z.string()),
  joined_at: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  syr_instance_url: z.string().optional()
})),
  total: z.number()
});
export type PageServerMember = z.infer<typeof PageServerMemberSchema>;

export const PageTrashMessageEntrySchema = z.object({
  items: z.array(z.object({
  id: z.string(),
  channel_id: z.string(),
  channel_name: z.string().optional(),
  sender_id: z.string(),
  sender_instance_url: z.string().optional(),
  content: z.string(),
  attachments: z.array(z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
})),
  created_at: z.string(),
  deleted_at: z.string(),
  deleted_by: z.string()
})),
  total: z.number()
});
export type PageTrashMessageEntry = z.infer<typeof PageTrashMessageEntrySchema>;

export const PaginatedQuerySchema = z.object({
  limit: z.number().optional(),
  offset: z.number().optional(),
  sort: z.string().optional(),
  order: z.string().optional(),
  q: z.string().optional()
});
export type PaginatedQuery = z.infer<typeof PaginatedQuerySchema>;

export const ParticipantRoleSchema = z.enum(['owner', 'admin', 'member']);
export type ParticipantRole = z.infer<typeof ParticipantRoleSchema>;

export const PendingFriendRequestSchema = z.object({
  did: z.string(),
  created_at: z.string()
});
export type PendingFriendRequest = z.infer<typeof PendingFriendRequestSchema>;

export const PermissionOverrideSchema = z.object({
  id: z.string(),
  server_id: z.string(),
  scope_type: z.enum(['server', 'category', 'channel']),
  scope_id: z.string().optional(),
  target_type: z.enum(['role', 'user']),
  target_id: z.string(),
  allow: z.string(),
  deny: z.string(),
  created_at: z.string(),
  updated_at: z.string()
});
export type PermissionOverride = z.infer<typeof PermissionOverrideSchema>;

export const PermissionScopeTypeSchema = z.enum(['server', 'category', 'channel']);
export type PermissionScopeType = z.infer<typeof PermissionScopeTypeSchema>;

export const PermissionTargetTypeSchema = z.enum(['role', 'user']);
export type PermissionTargetType = z.infer<typeof PermissionTargetTypeSchema>;

export const PermissionTreeSchema = z.object({
  server: z.object({
  permissions: z.string()
}),
  categories: z.array(z.object({
  id: z.string(),
  name: z.string(),
  position: z.number(),
  permissions: z.string(),
  channels: z.array(z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  position: z.number(),
  permissions: z.string(),
  can_view: z.boolean()
}))
})),
  uncategorized: z.array(z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  position: z.number(),
  permissions: z.string(),
  can_view: z.boolean()
}))
});
export type PermissionTree = z.infer<typeof PermissionTreeSchema>;

export const PermissionTreeCategorySchema = z.object({
  id: z.string(),
  name: z.string(),
  position: z.number(),
  permissions: z.string(),
  channels: z.array(z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  position: z.number(),
  permissions: z.string(),
  can_view: z.boolean()
}))
});
export type PermissionTreeCategory = z.infer<typeof PermissionTreeCategorySchema>;

export const PermissionTreeChannelSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  position: z.number(),
  permissions: z.string(),
  can_view: z.boolean()
});
export type PermissionTreeChannel = z.infer<typeof PermissionTreeChannelSchema>;

export const PermissionTreeServerSchema = z.object({
  permissions: z.string()
});
export type PermissionTreeServer = z.infer<typeof PermissionTreeServerSchema>;

export const PinMessageInputSchema = z.object({
  message_id: z.string()
});
export type PinMessageInput = z.infer<typeof PinMessageInputSchema>;

export const PresenceSchema = z.object({
  user_id: z.string(),
  status: z.enum(['online', 'idle', 'dnd', 'invisible', 'offline']),
  last_seen_at: z.string().optional(),
  custom_status: z.string().optional(),
  custom_emoji: z.string().optional()
});
export type Presence = z.infer<typeof PresenceSchema>;

export const PresenceStatusSchema = z.enum(['online', 'idle', 'dnd', 'invisible', 'offline']);
export type PresenceStatus = z.infer<typeof PresenceStatusSchema>;

export const PurgeMessagesInputSchema = z.object({
  delete_seconds: z.number()
});
export type PurgeMessagesInput = z.infer<typeof PurgeMessagesInputSchema>;

export const ReactionKindSchema = z.enum(['unicode', 'custom_emoji']);
export type ReactionKind = z.infer<typeof ReactionKindSchema>;

export const ReactionSummarySchema = z.object({
  value: z.string(),
  count: z.number(),
  me: z.boolean(),
  kind: z.string().optional(),
  image_url: z.string().optional()
});
export type ReactionSummary = z.infer<typeof ReactionSummarySchema>;

export const RelationsSnapshotSchema = z.object({
  friends: z.array(z.string()),
  incoming: z.array(z.object({
  did: z.string(),
  created_at: z.string()
})),
  outgoing: z.array(z.object({
  did: z.string(),
  created_at: z.string()
})),
  blocked: z.array(z.string()),
  ignored: z.array(z.string()),
  allow_dms: z.enum(['open', 'friends_only', 'closed']),
  allow_friend_requests: z.enum(['open', 'mutual', 'closed']),
  instances: z.record(z.string(), z.string())
});
export type RelationsSnapshot = z.infer<typeof RelationsSnapshotSchema>;

export const RemoveReactionInputSchema = z.object({
  value: z.string()
});
export type RemoveReactionInput = z.infer<typeof RemoveReactionInputSchema>;

export const RoleReorderInputSchema = z.object({
  roleIds: z.array(z.string())
});
export type RoleReorderInput = z.infer<typeof RoleReorderInputSchema>;

export const SendMessageInputSchema = z.object({
  content: z.string().optional(),
  reply_to: z.array(z.string()),
  attachments: z.array(z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
}))
});
export type SendMessageInput = z.infer<typeof SendMessageInputSchema>;

export const ServerSchema = z.object({
  id: z.string(),
  name: z.string(),
  icon_url: z.string().optional(),
  banner_url: z.string().optional(),
  invite_background_url: z.string().optional(),
  description: z.string().optional(),
  owner_id: z.string(),
  member_count: z.number(),
  created_at: z.string(),
  updated_at: z.string()
});
export type Server = z.infer<typeof ServerSchema>;

export const ServerBanSchema = z.object({
  id: z.string(),
  server_id: z.string(),
  user_id: z.string(),
  banned_by: z.string(),
  banned_at: z.string(),
  reason: z.string().optional(),
  active: z.boolean(),
  unbanned_at: z.string().optional(),
  unbanned_by: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
});
export type ServerBan = z.infer<typeof ServerBanSchema>;

export const ServerInviteSchema = z.object({
  id: z.string(),
  server_id: z.string(),
  code: z.string(),
  created_by: z.string(),
  expires_at: z.string().optional(),
  max_uses: z.number(),
  uses: z.number(),
  target_kind: z.enum(['open', 'instance', 'did']),
  target_value: z.string().optional(),
  label: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
});
export type ServerInvite = z.infer<typeof ServerInviteSchema>;

export const ServerMemberSchema = z.object({
  id: z.string(),
  server_id: z.string(),
  user_id: z.string(),
  nickname: z.string().optional(),
  role_ids: z.array(z.string()),
  joined_at: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  syr_instance_url: z.string().optional()
});
export type ServerMember = z.infer<typeof ServerMemberSchema>;

export const ServerRoleSchema = z.object({
  id: z.string(),
  server_id: z.string(),
  name: z.string(),
  color: z.string().optional(),
  position: z.number(),
  permissions: z.string(),
  permissions_allow: z.string(),
  permissions_deny: z.string(),
  is_default: z.boolean(),
  deleted: z.boolean(),
  deleted_at: z.string().optional(),
  deleted_by: z.string().optional(),
  created_at: z.string(),
  updated_at: z.string()
});
export type ServerRole = z.infer<typeof ServerRoleSchema>;

export const SuccessResponseSchema = z.object({
  success: z.boolean()
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

export const TransferOwnershipInputSchema = z.object({
  new_owner_id: z.string()
});
export type TransferOwnershipInput = z.infer<typeof TransferOwnershipInputSchema>;

export const TransferOwnershipResponseSchema = z.object({
  server: z.object({
  id: z.string(),
  name: z.string(),
  icon_url: z.string().optional(),
  banner_url: z.string().optional(),
  invite_background_url: z.string().optional(),
  description: z.string().optional(),
  owner_id: z.string(),
  member_count: z.number(),
  created_at: z.string(),
  updated_at: z.string()
}),
  former_owner_role_id: z.string()
});
export type TransferOwnershipResponse = z.infer<typeof TransferOwnershipResponseSchema>;

export const TrashChannelEntrySchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string(),
  deleted_at: z.string(),
  deleted_by: z.string(),
  message_count: z.number()
});
export type TrashChannelEntry = z.infer<typeof TrashChannelEntrySchema>;

export const TrashMessageEntrySchema = z.object({
  id: z.string(),
  channel_id: z.string(),
  channel_name: z.string().optional(),
  sender_id: z.string(),
  sender_instance_url: z.string().optional(),
  content: z.string(),
  attachments: z.array(z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
})),
  created_at: z.string(),
  deleted_at: z.string(),
  deleted_by: z.string()
});
export type TrashMessageEntry = z.infer<typeof TrashMessageEntrySchema>;

export const TrashRoleEntrySchema = z.object({
  id: z.string(),
  name: z.string(),
  color: z.string().optional(),
  deleted_at: z.string(),
  deleted_by: z.string(),
  member_count: z.number()
});
export type TrashRoleEntry = z.infer<typeof TrashRoleEntrySchema>;

export const UpdateCategoryInputSchema = z.object({
  name: z.string().optional()
});
export type UpdateCategoryInput = z.infer<typeof UpdateCategoryInputSchema>;

export const UpdateChannelInputSchema = z.object({
  name: z.string().optional(),
  topic: z.string().optional(),
  category_id: z.string().optional()
});
export type UpdateChannelInput = z.infer<typeof UpdateChannelInputSchema>;

export const UpdateInviteInputSchema = z.object({
  label: z.string().optional()
});
export type UpdateInviteInput = z.infer<typeof UpdateInviteInputSchema>;

export const UpdateMyselfInputSchema = z.object({
  allow_dms: z.enum(['open', 'friends_only', 'closed']).optional(),
  allow_friend_requests: z.enum(['open', 'mutual', 'closed']).optional(),
  display_name: z.string().optional(),
  bio: z.string().optional(),
  avatar_url: z.string().optional()
});
export type UpdateMyselfInput = z.infer<typeof UpdateMyselfInputSchema>;

export const UpdateMyselfPolicyInputSchema = z.object({
  trusted_domains: z.array(z.string()).optional(),
  allow_dms: z.enum(['open', 'friends_only', 'closed']).optional(),
  allow_friend_requests: z.enum(['open', 'mutual', 'closed']).optional()
});
export type UpdateMyselfPolicyInput = z.infer<typeof UpdateMyselfPolicyInputSchema>;

export const UpdateRoleInputSchema = z.object({
  name: z.string().optional(),
  color: z.string().optional(),
  permissions: z.string().optional(),
  permissions_allow: z.string().optional(),
  permissions_deny: z.string().optional(),
  position: z.number().optional()
});
export type UpdateRoleInput = z.infer<typeof UpdateRoleInputSchema>;

export const UpdateServerInputSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  icon_url: z.string().optional(),
  banner_url: z.string().optional(),
  invite_background_url: z.string().optional()
});
export type UpdateServerInput = z.infer<typeof UpdateServerInputSchema>;

export const UploadFinalizeInputSchema = z.object({
  sha256: z.string().optional(),
  width: z.number().optional(),
  height: z.number().optional()
});
export type UploadFinalizeInput = z.infer<typeof UploadFinalizeInputSchema>;

export const UploadFinalizeResponseSchema = z.object({
  url: z.string(),
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  width: z.number().optional(),
  height: z.number().optional()
});
export type UploadFinalizeResponse = z.infer<typeof UploadFinalizeResponseSchema>;

export const UploadPresignInputSchema = z.object({
  filename: z.string(),
  mime_type: z.string(),
  size: z.number(),
  channel_id: z.string().optional(),
  sha256: z.string().optional()
});
export type UploadPresignInput = z.infer<typeof UploadPresignInputSchema>;

export const UploadPresignResponseSchema = z.object({
  upload_id: z.string(),
  signed_url: z.string(),
  final_url: z.string(),
  max_bytes: z.number()
});
export type UploadPresignResponse = z.infer<typeof UploadPresignResponseSchema>;

export const UpsertOverrideInputSchema = z.object({
  scope_type: z.enum(['server', 'category', 'channel']),
  scope_id: z.string().optional(),
  target_type: z.enum(['role', 'user']),
  target_id: z.string(),
  allow: z.string(),
  deny: z.string()
});
export type UpsertOverrideInput = z.infer<typeof UpsertOverrideInputSchema>;

export const UserSchema = z.object({
  id: z.string(),
  syr_id: z.string(),
  did: z.string().optional(),
  handle: z.string(),
  display_name: z.string().optional(),
  avatar_url: z.string().optional(),
  bio: z.string().optional(),
  syr_instance_url: z.string().optional(),
  delegate_public_key: z.string().optional(),
  last_seen_at: z.string().optional(),
  is_online: z.boolean(),
  has_instance: z.boolean(),
  allow_dms: z.enum(['open', 'friends_only', 'closed']),
  allow_friend_requests: z.enum(['open', 'mutual', 'closed']),
  created_at: z.string(),
  updated_at: z.string()
});
export type User = z.infer<typeof UserSchema>;

export const UserBlockSchema = z.object({
  id: z.string(),
  blocker_id: z.string(),
  blocked_id: z.string(),
  created_at: z.string(),
  updated_at: z.string()
});
export type UserBlock = z.infer<typeof UserBlockSchema>;

export const UserIdInputSchema = z.object({
  user_id: z.string()
});
export type UserIdInput = z.infer<typeof UserIdInputSchema>;

export const UserIgnoreSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  ignored_id: z.string(),
  created_at: z.string(),
  updated_at: z.string()
});
export type UserIgnore = z.infer<typeof UserIgnoreSchema>;

export const UserResolveResultSchema = z.object({
  did: z.string(),
  syr_instance_url: z.string().optional(),
  registered: z.boolean()
});
export type UserResolveResult = z.infer<typeof UserResolveResultSchema>;

export const VisibleChannelSummarySchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.string()
});
export type VisibleChannelSummary = z.infer<typeof VisibleChannelSummarySchema>;

export const VoiceStateSchema = z.object({
  user_id: z.string(),
  channel_id: z.string(),
  server_id: z.string(),
  self_mute: z.boolean(),
  self_deaf: z.boolean(),
  has_camera: z.boolean(),
  has_screen: z.boolean()
});
export type VoiceState = z.infer<typeof VoiceStateSchema>;

export const VoiceTokenInputSchema = z.object({
  channel_id: z.string()
});
export type VoiceTokenInput = z.infer<typeof VoiceTokenInputSchema>;

export const VoiceTokenResponseSchema = z.object({
  token: z.string(),
  url: z.string()
});
export type VoiceTokenResponse = z.infer<typeof VoiceTokenResponseSchema>;

export const WsBlockUpdatePayloadSchema = z.object({
  did: z.string(),
  blocked: z.boolean()
});
export type WsBlockUpdatePayload = z.infer<typeof WsBlockUpdatePayloadSchema>;

export const WsCategoryDeletePayloadSchema = z.object({
  id: z.string(),
  server_id: z.string().optional()
});
export type WsCategoryDeletePayload = z.infer<typeof WsCategoryDeletePayloadSchema>;

export const WsChannelDeletePayloadSchema = z.object({
  id: z.string(),
  server_id: z.string().optional()
});
export type WsChannelDeletePayload = z.infer<typeof WsChannelDeletePayloadSchema>;

export const WsDmPolicyUpdatePayloadSchema = z.object({
  allow_dms: z.enum(['open', 'friends_only', 'closed']),
  allow_friend_requests: z.enum(['open', 'mutual', 'closed'])
});
export type WsDmPolicyUpdatePayload = z.infer<typeof WsDmPolicyUpdatePayloadSchema>;

export const WsEnvelopeSchema = z.object({
  op: z.number(),
  d: z.any()
});
export type WsEnvelope = z.infer<typeof WsEnvelopeSchema>;

export const WsFriendRequestReceivePayloadSchema = z.object({
  from: z.string(),
  created_at: z.string()
});
export type WsFriendRequestReceivePayload = z.infer<typeof WsFriendRequestReceivePayloadSchema>;

export const WsFriendRequestUpdatePayloadSchema = z.object({
  did: z.string(),
  status: z.string()
});
export type WsFriendRequestUpdatePayload = z.infer<typeof WsFriendRequestUpdatePayloadSchema>;

export const WsIdentifyPayloadSchema = z.object({
  token: z.string()
});
export type WsIdentifyPayload = z.infer<typeof WsIdentifyPayloadSchema>;

export const WsIgnoreUpdatePayloadSchema = z.object({
  did: z.string(),
  ignored: z.boolean()
});
export type WsIgnoreUpdatePayload = z.infer<typeof WsIgnoreUpdatePayloadSchema>;

export const WsMemberRemovePayloadSchema = z.object({
  server_id: z.string(),
  user_id: z.string()
});
export type WsMemberRemovePayload = z.infer<typeof WsMemberRemovePayloadSchema>;

export const WsMessageDeletePayloadSchema = z.object({
  channel_id: z.string(),
  message_id: z.string(),
  deleted_by: z.string().optional()
});
export type WsMessageDeletePayload = z.infer<typeof WsMessageDeletePayloadSchema>;

export const WsPinPayloadSchema = z.object({
  channel_id: z.string(),
  message_id: z.string()
});
export type WsPinPayload = z.infer<typeof WsPinPayloadSchema>;

export const WsPresenceUpdateBroadcastPayloadSchema = z.object({
  user_id: z.string(),
  status: z.enum(['online', 'idle', 'dnd', 'invisible', 'offline']),
  custom_status: z.string().optional()
});
export type WsPresenceUpdateBroadcastPayload = z.infer<typeof WsPresenceUpdateBroadcastPayloadSchema>;

export const WsPresenceUpdatePayloadSchema = z.object({
  status: z.enum(['online', 'idle', 'dnd', 'invisible', 'offline']),
  custom_status: z.string().optional()
});
export type WsPresenceUpdatePayload = z.infer<typeof WsPresenceUpdatePayloadSchema>;

export const WsProfileUpdatePayloadSchema = z.object({
  did: z.string()
});
export type WsProfileUpdatePayload = z.infer<typeof WsProfileUpdatePayloadSchema>;

export const WsReactionPayloadSchema = z.object({
  channel_id: z.string(),
  message_id: z.string(),
  user_id: z.string(),
  kind: z.enum(['unicode', 'custom_emoji']),
  value: z.string(),
  image_url: z.string().optional()
});
export type WsReactionPayload = z.infer<typeof WsReactionPayloadSchema>;

export const WsReadyChannelSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  type: z.string(),
  position: z.number()
});
export type WsReadyChannel = z.infer<typeof WsReadyChannelSchema>;

export const WsReadyDmChannelSchema = z.object({
  id: z.string(),
  participants: z.array(z.string())
});
export type WsReadyDmChannel = z.infer<typeof WsReadyDmChannelSchema>;

export const WsReadyPayloadSchema = z.object({
  user_id: z.string(),
  servers: z.array(z.object({
  id: z.string(),
  name: z.string(),
  icon_url: z.string().optional(),
  channels: z.array(z.object({
  id: z.string(),
  name: z.string().optional(),
  type: z.string(),
  position: z.number()
}))
})),
  dm_channels: z.array(z.object({
  id: z.string(),
  participants: z.array(z.string())
})),
  presences: z.array(z.object({
  user_id: z.string(),
  status: z.enum(['online', 'idle', 'dnd', 'invisible', 'offline'])
})),
  unread: z.array(z.object({
  channel_id: z.string(),
  count: z.number(),
  mention_count: z.number()
}))
});
export type WsReadyPayload = z.infer<typeof WsReadyPayloadSchema>;

export const WsReadyPresenceSchema = z.object({
  user_id: z.string(),
  status: z.enum(['online', 'idle', 'dnd', 'invisible', 'offline'])
});
export type WsReadyPresence = z.infer<typeof WsReadyPresenceSchema>;

export const WsReadyServerSchema = z.object({
  id: z.string(),
  name: z.string(),
  icon_url: z.string().optional(),
  channels: z.array(z.object({
  id: z.string(),
  name: z.string().optional(),
  type: z.string(),
  position: z.number()
}))
});
export type WsReadyServer = z.infer<typeof WsReadyServerSchema>;

export const WsReadyUnreadSchema = z.object({
  channel_id: z.string(),
  count: z.number(),
  mention_count: z.number()
});
export type WsReadyUnread = z.infer<typeof WsReadyUnreadSchema>;

export const WsRoleDeletePayloadSchema = z.object({
  id: z.string(),
  server_id: z.string()
});
export type WsRoleDeletePayload = z.infer<typeof WsRoleDeletePayloadSchema>;

export const WsServerDeletePayloadSchema = z.object({
  id: z.string()
});
export type WsServerDeletePayload = z.infer<typeof WsServerDeletePayloadSchema>;

export const WsSubscribePayloadSchema = z.object({
  channel_ids: z.array(z.string())
});
export type WsSubscribePayload = z.infer<typeof WsSubscribePayloadSchema>;

export const WsTypingStartBroadcastPayloadSchema = z.object({
  channel_id: z.string(),
  user_id: z.string()
});
export type WsTypingStartBroadcastPayload = z.infer<typeof WsTypingStartBroadcastPayloadSchema>;

export const WsTypingStartPayloadSchema = z.object({
  channel_id: z.string()
});
export type WsTypingStartPayload = z.infer<typeof WsTypingStartPayloadSchema>;

export const WsUnwatchProfilesPayloadSchema = z.object({
  dids: z.array(z.string())
});
export type WsUnwatchProfilesPayload = z.infer<typeof WsUnwatchProfilesPayloadSchema>;

export const WsVoiceStateUpdatePayloadSchema = z.object({
  channel_id: z.string().optional(),
  self_mute: z.boolean(),
  self_deaf: z.boolean()
});
export type WsVoiceStateUpdatePayload = z.infer<typeof WsVoiceStateUpdatePayloadSchema>;

export const WsWatchProfileEntrySchema = z.object({
  did: z.string(),
  instance_url: z.string()
});
export type WsWatchProfileEntry = z.infer<typeof WsWatchProfileEntrySchema>;

export const WsWatchProfilesPayloadSchema = z.object({
  profiles: z.array(z.object({
  did: z.string(),
  instance_url: z.string()
}))
});
export type WsWatchProfilesPayload = z.infer<typeof WsWatchProfilesPayloadSchema>;

