/**
 * WebSocket opcodes.
 *
 * The numeric values match `packages/rust/syren-types/src/ws.rs::WsOp`.
 * The dictionary form is preserved here (uppercase keys) because the
 * existing UI / app-core / api code addresses ops as `WsOp.MESSAGE_CREATE`
 * etc. Wire format stays `{ op: number, d: payload }`; the typed payload
 * shapes live in `./generated.ts`.
 */
export const WsOp = {
	IDENTIFY: 1,
	HEARTBEAT: 2,
	SUBSCRIBE: 3,
	UNSUBSCRIBE: 4,
	TYPING_START: 5,
	PRESENCE_UPDATE: 6,
	VOICE_STATE_UPDATE: 7,

	READY: 10,
	HEARTBEAT_ACK: 11,
	MESSAGE_CREATE: 20,
	MESSAGE_UPDATE: 21,
	MESSAGE_DELETE: 22,
	TYPING_START_BROADCAST: 25,
	PRESENCE_UPDATE_BROADCAST: 26,
	CHANNEL_CREATE: 28,
	CHANNEL_DELETE: 29,
	CHANNEL_UPDATE: 30,
	MEMBER_UPDATE: 31,
	MEMBER_REMOVE: 32,
	ROLE_CREATE: 33,
	ROLE_UPDATE: 34,
	ROLE_DELETE: 35,
	VOICE_STATE_UPDATE_BROADCAST: 36,
	SERVER_UPDATE: 37,
	SERVER_DELETE: 38,
	REACTION_ADD: 40,
	REACTION_REMOVE: 41,
	PIN_ADD: 42,
	PIN_REMOVE: 43,
	AUDIT_LOG_APPEND: 44,
	PERMISSION_OVERRIDE_UPDATE: 45,
	CATEGORY_CREATE: 46,
	CATEGORY_UPDATE: 47,
	CATEGORY_DELETE: 48,

	WATCH_PROFILES: 50,
	UNWATCH_PROFILES: 51,
	PROFILE_UPDATE: 52,

	FRIEND_REQUEST_RECEIVE: 53,
	FRIEND_REQUEST_UPDATE: 54,
	BLOCK_UPDATE: 55,
	IGNORE_UPDATE: 56,
	DM_POLICY_UPDATE: 57,
	DM_CHANNEL_CREATE: 58
} as const;
